kind: pipeline
name: lds-gsim-browser

trigger:
  branch:
    - master

steps:
  - name: install
    image: node:current-alpine
    commands:
      - yarn install
    when:
      event:
        - push

  - name: test-and-build
    image: node:current-alpine
    commands:
      - CI=true yarn test
      - CI=true yarn build
    when:
      event:
        - push

  - name: publish-docker
    image: plugins/gcr
    settings:
      repo: prod-bip/lds-gsim-browser
      registry: eu.gcr.io
      tags: "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
      json_key:
        from_secret: gcr_credentials
    when:
      event:
        - push

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_url
#      channel: bip-ci-test -- Choosing channel is not enabled yet
    when:
      status: [ success, failure ]

---
kind: secret
name: gcr_credentials
get:
  path: drone-gcr-credentials
  name: gcr-credentials

---
kind: secret
name: slack_webhook_url
get:
  path: drone-slack-webhook-url
  name: slack-webhook-url